
name: Build 
on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs: 
    build:
        runs-on: ${{ matrix.os }}
        strategy: 
          fail-fast: false
          matrix: 
            os: [ubuntu-latest, macos-latest, windows-latest]
            build_type: [Release, Debug]
            c_compiler: [gcc, clang]
            cpp_compiler: [g++, clang++]
        steps:
        - uses: actions/checkout@v4
        
        - name: Configure and build ADOL-C
          run: |
            mkdir build
            cd build
            cmake \
            -DCMAKE_CXX_COMPILER= ${{ matrix.cpp_compiler}} \
            -DCMAKE_C_COMPILER= ${{ matrix.c_compiler}} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DBUILD_TESTS=ON \
            -S .. \
            -B .
            cmake --build .
        


        