on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Install Boost
      shell: bash
      run: |
        sudo apt-get install libboost-all-dev

    - name: Configure and build ADOL-C
      run: |
        mkdir build
        cd build
        cmake \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_BUILD_TYPE=TestsWithCov \
        -S .. \
        -B .
        cmake --build .
    
    - name: Run Tests
      run: |
        set +e # otherwise the coverage report fails if ctest finds errors
        ctest --test-dir build/
        exit 0

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}