name: Run clang-format Linter

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Clang-Format
        run: sudo apt-get install -y clang-format

      - name: Check formatting with Clang-Format
        run: |
          FILES=$(git ls-files '*.c' '*.cpp' '*.h' '*.hpp')
          clang-format --dry-run -Werror $FILES
