
name: Run Tests
on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs: 
    run-tests: 
        runs-on: ubuntu-latest
        strategy: 
          fail-fast: false
          matrix: 
            build_type: [Release, Debug]
            c_compiler: [gcc, clang]
            cpp_compiler: [g++, clang++]

        steps:
        - uses: actions/checkout@v4
        
        - name: Install Boost
          shell: bash
          run: |
            sudo apt-get install libboost-all-dev

        - name: Configure and build ADOL-C
          run: |
            mkdir build
            cd build
            cmake \
            -DCMAKE_CXX_COMPILER= ${{ matrix.cpp_compiler}} \
            -DCMAKE_C_COMPILER= ${{ matrix.c_compiler}} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DBUILD_TESTS=ON \
            -S .. \
            -B .
            cmake --build .
        
        - name: Run Tests
          run: ctest --test-dir build/ --output-on-failure


        