
name: Run Tests
on:
    push:
      branches: [ "workflows" ]
    pull_request:
      branches: [ "workflows" ]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Build ADOL-C
          run: >  
            cmake -B ${{ steps.strings.outputs.build-output-dir }}
            -DCMAKE_CXX_COMPILER=g++
            -DCMAKE_C_COMPILER=gcc
            -DCMAKE_BUILD_TYPE=Release
            -S ${{ github.workspace }}
    
        - name: Install Boost
          shell: bash
          run: |
            sudo apt-get install libboost-all-dev

        - name: Build Boost-Test
          shell: bash
          run: |
            ls
            cd ADOL-C/ADOL-C/boost-test
            mkdir build && cd build
            cmake ../ -DADOLC_BASE=${{ github.workspace }}