
name: Run Tests
on:
    push:
      branches: [ "workflows" ]
    pull_request:
      branches: [ "workflows" ]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
  
        - name: Configure CMake ADOL-C
          run: >  
            cmake
            -DCMAKE_CXX_COMPILER=g++
            -DCMAKE_C_COMPILER=gcc
            -DCMAKE_BUILD_TYPE=Release
            -S ${{ github.workspace }}
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }} 

        - name: Build ADOLC
          run: |
            make
            make install
        
        - name: Install Boost
          shell: bash
          run: |
            sudo apt-get install libboost-all-dev

        - name: Build Boost-Test
          shell: bash
          run: |
            ls ${{ github.workspace }}
            cd ADOL-C/boost-test
            mkdir build && cd build
            cmake ../ -DADOLC_BASE=${{ github.workspace }}