
name: Run Tests
on:
    push:
      branches: [ "workflows" ]
    pull_request:
      branches: [ "workflows" ]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set reusable strings
          # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
          id: strings
          shell: bash
          run: |
            echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
  
        - name: Configure CMake ADOL-C
          run: >  
            cmake -B ${{ steps.strings.outputs.build-output-dir }}
            -DCMAKE_CXX_COMPILER=g++
            -DCMAKE_C_COMPILER=gcc
            -DCMAKE_BUILD_TYPE=Release
            -S ${{ github.workspace }}
            - name: Build
        - name: Build ADOLC
          run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release
        
        - name: Install Boost
          shell: bash
          run: |
            sudo apt-get install libboost-all-dev

        - name: Build Boost-Test
          shell: bash
          run: |
            ls build
            cd ADOL-C/boost-test
            mkdir build && cd build
            cmake ../ -DADOLC_BASE=${{ steps.strings.outputs.build-output-dir }}